- sourcename: Consider the Lobster
  author: David Foster Wallace
- sourcename: Downton Abbey
- sourcename: Half Empty
  author: David Rakoff
- sourcename: Scrubs, Season 4, My Common Enemy
  author: Dr. Kelso
- sourcename: Scrubs, Season 2, Fruit Cups
  author: J. D.
- sourcename: The Elements of Typographic Style
  author: Robert Bringhurst
